In [13]:
import pandas as pd
import os


os.makedirs(
    "results",
    exist_ok=True
)

In [19]:
crop_results = {

    "Rank": [
        1,2,3,4,5,6,7,8,9
    ],

    "Model": [

        "Extra Trees",
        "Random Forest",
        "Voting Ensemble",
        "XGBoost",
        "Stacking Ensemble",
        "Decision Tree",
        "KNN",
        "SVM",
        "Logistic Regression"

    ],


    "Task": [

        "Multi-Class Classification"

    ] * 9,


    "Accuracy (%)": [

        99.5454,
        99.3181,
        99.3181,
        98.8636,
        98.8636,
        98.6363,
        97.0454,
        96.1363,
        95.9090

    ],


    "Selection Status": [

        "Winner - Selected Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model"

    ]

}


crop_df = pd.DataFrame(
    crop_results
)


crop_df.to_csv(
    "results/crop_model_analysis.csv",
    index=False
)


crop_df

,Rank,Model,Task,Accuracy (%),Selection Status
0,1,Extra Trees,Multi-Class Classification,99.5454,Winner - Selected Model
1,2,Random Forest,Multi-Class Classification,99.3181,Compared Model
2,3,Voting Ensemble,Multi-Class Classification,99.3181,Compared Model
3,4,XGBoost,Multi-Class Classification,98.8636,Compared Model
4,5,Stacking Ensemble,Multi-Class Classification,98.8636,Compared Model
5,6,Decision Tree,Multi-Class Classification,98.6363,Compared Model
6,7,KNN,Multi-Class Classification,97.0454,Compared Model
7,8,SVM,Multi-Class Classification,96.1363,Compared Model
8,9,Logistic Regression,Multi-Class Classification,95.9090,Compared Model

In [20]:
fertilizer_results = {


    "Rank": [
        1,2,3,4,5,6,7,8,9,10,11
    ],


    "Model": [

        "XGBoost",
        "Gradient Boosting",
        "Random Forest",
        "Decision Tree",
        "Tuned XGBoost",
        "Stacking Ensemble",
        "Voting Ensemble",
        "CatBoost",
        "Balanced Random Forest",
        "Extra Trees",
        "SVM"

    ],


    "Task": [

        "Multi-Class Classification"

    ] * 11,


    "Accuracy (%)": [

        88.55,
        88.55,
        88.35,
        88.20,
        87.45,
        87.40,
        87.40,
        87.05,
        86.60,
        85.50,
        56.85

    ],


    "Selection Status": [

        "Winner - Selected Model",
        "Equivalent Accuracy",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Better Minority Class Handling",
        "Compared Model",
        "Compared Model"

    ]

}


fertilizer_df = pd.DataFrame(
    fertilizer_results
)


fertilizer_df.to_csv(
    "results/fertilizer_model_analysis.csv",
    index=False
)


fertilizer_df

,Rank,Model,Task,Accuracy (%),Selection Status
0,1,XGBoost,Multi-Class Classification,88.55,Winner - Selected Model
1,2,Gradient Boosting,Multi-Class Classification,88.55,Equivalent Accuracy
2,3,Random Forest,Multi-Class Classification,88.35,Compared Model
3,4,Decision Tree,Multi-Class Classification,88.20,Compared Model
4,5,Tuned XGBoost,Multi-Class Classification,87.45,Compared Model
5,6,Stacking Ensemble,Multi-Class Classification,87.40,Compared Model
6,7,Voting Ensemble,Multi-Class Classification,87.40,Compared Model
7,8,CatBoost,Multi-Class Classification,87.05,Compared Model
8,9,Balanced Random Forest,Multi-Class Classification,86.60,Better Minority Class Handling
9,10,Extra Trees,Multi-Class Classification,85.50,Compared Model
10,11,SVM,Multi-Class Classification,56.85,Compared Model

In [21]:
price_results = {


    "Rank": [
        1,2,3,4,5,6,7,8,9
    ],


    "Model": [

        "Gradient Boosting",
        "Stacking Ensemble",
        "XGBoost",
        "Voting Ensemble",
        "Random Forest",
        "Hist Gradient Boosting",
        "CatBoost",
        "LightGBM",
        "Extra Trees"

    ],


    "Task": [

        "Regression"

    ] * 9,


    "R2 Score": [

        0.8413524895,
        0.8275262247,
        0.7856223583,
        0.6861275494,
        0.6773009305,
        0.6129074828,
        0.4812792161,
        0.4675704356,
        0.3552792685

    ],


    "MAE": [

        1006.998,
        938.010,
        1002.656,
        1096.585,
        1113.718,
        1161.131,
        1220.145,
        1279.799,
        1255.808

    ],


    "RMSE": [

        1880.104,
        1960.319,
        2185.521,
        2644.489,
        2681.415,
        2936.788,
        3399.633,
        3444.263,
        3790.103

    ],


    "Selection Status": [

        "Winner - Selected Model",
        "Best MAE",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model",
        "Compared Model"

    ]

}


price_df = pd.DataFrame(
    price_results
)


price_df.to_csv(
    "results/price_model_analysis.csv",
    index=False
)


price_df

,Rank,Model,Task,R2 Score,MAE,RMSE,Selection Status
0,1,Gradient Boosting,Regression,0.841352,1006.998,1880.104,Winner - Selected Model
1,2,Stacking Ensemble,Regression,0.827526,938.010,1960.319,Best MAE
2,3,XGBoost,Regression,0.785622,1002.656,2185.521,Compared Model
3,4,Voting Ensemble,Regression,0.686128,1096.585,2644.489,Compared Model
4,5,Random Forest,Regression,0.677301,1113.718,2681.415,Compared Model
5,6,Hist Gradient Boosting,Regression,0.612907,1161.131,2936.788,Compared Model
6,7,CatBoost,Regression,0.481279,1220.145,3399.633,Compared Model
7,8,LightGBM,Regression,0.467570,1279.799,3444.263,Compared Model
8,9,Extra Trees,Regression,0.355279,1255.808,3790.103,Compared Model

In [22]:
overall_results = {


    "Module": [

        "Crop Recommendation",
        "Fertilizer Recommendation",
        "Market Price Prediction"

    ],


    "Selected Model": [

        "Extra Trees Classifier",
        "XGBoost Classifier",
        "Gradient Boosting Regressor"

    ],


    "Problem Type": [

        "Multi-Class Classification",
        "Multi-Class Classification",
        "Regression"

    ],


    "Evaluation Metric": [

        "Accuracy",
        "Accuracy",
        "R² Score"

    ],


    "Performance": [

        "99.5454%",
        "88.55%",
        "0.841352"

    ],


    "Additional Evaluation": [

        "Precision, Recall, F1-Score ≈ 1.00",
        "Precision, Recall, F1-Score evaluated",
        "MAE = 1006.998, RMSE = 1880.104"

    ],


    "Selection Reason": [

        "Highest classification accuracy among crop models",
        "Best accuracy and strong performance on fertilizer dataset",
        "Highest R² score with lowest prediction error balance"

    ]

}


overall_df = pd.DataFrame(
    overall_results
)


overall_df.to_csv(
    "results/final_proposed_system_comparison.csv",
    index=False
)


overall_df

,Module,Selected Model,Problem Type,Evaluation Metric,Performance,Additional Evaluation,Selection Reason
0,Crop Recommendation,Extra Trees Classifier,Multi-Class Classification,Accuracy,99.5454%,"Precision, Recall, F1-Score ≈ 1.00",Highest classification accuracy among crop models
1,Fertilizer Recommendation,XGBoost Classifier,Multi-Class Classification,Accuracy,88.55%,"Precision, Recall, F1-Score evaluated",Best accuracy and strong performance on fertil...
2,Market Price Prediction,Gradient Boosting Regressor,Regression,R² Score,0.841352,"MAE = 1006.998, RMSE = 1880.104",Highest R² score with lowest prediction error ...